// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/antongolenev23/tuchka-server/internal/entity"
	"github.com/antongolenev23/tuchka-server/internal/http-server/handler/dto"
	"github.com/antongolenev23/tuchka-server/internal/repository/model"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRepository
func (_mock *MockRepository) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Close() *MockRepository_Close_Call {
	return &MockRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRepository_Close_Call) Run(run func()) *MockRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Close_Call) Return(err error) *MockRepository_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Close_Call) RunAndReturn(run func() error) *MockRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(user entity.User) (uuid.UUID, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entity.User) (uuid.UUID, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(entity.User) uuid.UUID); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(entity.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user entity.User
func (_e *MockRepository_Expecter) Create(user interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockRepository_Create_Call) Run(run func(user entity.User)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.User
		if args[0] != nil {
			arg0 = args[0].(entity.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(uUID uuid.UUID, err error) *MockRepository_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(user entity.User) (uuid.UUID, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFileMetadata provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteFileMetadata(name string, userID uuid.UUID) error {
	ret := _mock.Called(name, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFileMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, uuid.UUID) error); ok {
		r0 = returnFunc(name, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFileMetadata'
type MockRepository_DeleteFileMetadata_Call struct {
	*mock.Call
}

// DeleteFileMetadata is a helper method to define mock.On call
//   - name string
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) DeleteFileMetadata(name interface{}, userID interface{}) *MockRepository_DeleteFileMetadata_Call {
	return &MockRepository_DeleteFileMetadata_Call{Call: _e.mock.On("DeleteFileMetadata", name, userID)}
}

func (_c *MockRepository_DeleteFileMetadata_Call) Run(run func(name string, userID uuid.UUID)) *MockRepository_DeleteFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteFileMetadata_Call) Return(err error) *MockRepository_DeleteFileMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteFileMetadata_Call) RunAndReturn(run func(name string, userID uuid.UUID) error) *MockRepository_DeleteFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByEmail(email string) (entity.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (entity.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) entity.User); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Get(0).(entity.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) GetByEmail(email interface{}) *MockRepository_GetByEmail_Call {
	return &MockRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *MockRepository_GetByEmail_Call) Run(run func(email string)) *MockRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetByEmail_Call) Return(user entity.User, err error) *MockRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetByEmail_Call) RunAndReturn(run func(email string) (entity.User, error)) *MockRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilePath provides a mock function for the type MockRepository
func (_mock *MockRepository) GetFilePath(name string, userID uuid.UUID) (string, error) {
	ret := _mock.Called(name, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilePath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uuid.UUID) (string, error)); ok {
		return returnFunc(name, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uuid.UUID) string); ok {
		r0 = returnFunc(name, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, uuid.UUID) error); ok {
		r1 = returnFunc(name, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetFilePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilePath'
type MockRepository_GetFilePath_Call struct {
	*mock.Call
}

// GetFilePath is a helper method to define mock.On call
//   - name string
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) GetFilePath(name interface{}, userID interface{}) *MockRepository_GetFilePath_Call {
	return &MockRepository_GetFilePath_Call{Call: _e.mock.On("GetFilePath", name, userID)}
}

func (_c *MockRepository_GetFilePath_Call) Run(run func(name string, userID uuid.UUID)) *MockRepository_GetFilePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetFilePath_Call) Return(s string, err error) *MockRepository_GetFilePath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_GetFilePath_Call) RunAndReturn(run func(name string, userID uuid.UUID) (string, error)) *MockRepository_GetFilePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilePaths provides a mock function for the type MockRepository
func (_mock *MockRepository) GetFilePaths(downloadReq dto.FilesList, userID uuid.UUID) ([]entity.FilePath, error) {
	ret := _mock.Called(downloadReq, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilePaths")
	}

	var r0 []entity.FilePath
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(dto.FilesList, uuid.UUID) ([]entity.FilePath, error)); ok {
		return returnFunc(downloadReq, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.FilesList, uuid.UUID) []entity.FilePath); ok {
		r0 = returnFunc(downloadReq, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.FilePath)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(dto.FilesList, uuid.UUID) error); ok {
		r1 = returnFunc(downloadReq, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetFilePaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilePaths'
type MockRepository_GetFilePaths_Call struct {
	*mock.Call
}

// GetFilePaths is a helper method to define mock.On call
//   - downloadReq dto.FilesList
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) GetFilePaths(downloadReq interface{}, userID interface{}) *MockRepository_GetFilePaths_Call {
	return &MockRepository_GetFilePaths_Call{Call: _e.mock.On("GetFilePaths", downloadReq, userID)}
}

func (_c *MockRepository_GetFilePaths_Call) Run(run func(downloadReq dto.FilesList, userID uuid.UUID)) *MockRepository_GetFilePaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.FilesList
		if args[0] != nil {
			arg0 = args[0].(dto.FilesList)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetFilePaths_Call) Return(filePaths []entity.FilePath, err error) *MockRepository_GetFilePaths_Call {
	_c.Call.Return(filePaths, err)
	return _c
}

func (_c *MockRepository_GetFilePaths_Call) RunAndReturn(run func(downloadReq dto.FilesList, userID uuid.UUID) ([]entity.FilePath, error)) *MockRepository_GetFilePaths_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilesMetadata provides a mock function for the type MockRepository
func (_mock *MockRepository) GetFilesMetadata(userID uuid.UUID) ([]dto.MetadataOutput, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesMetadata")
	}

	var r0 []dto.MetadataOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) ([]dto.MetadataOutput, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) []dto.MetadataOutput); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.MetadataOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetFilesMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesMetadata'
type MockRepository_GetFilesMetadata_Call struct {
	*mock.Call
}

// GetFilesMetadata is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) GetFilesMetadata(userID interface{}) *MockRepository_GetFilesMetadata_Call {
	return &MockRepository_GetFilesMetadata_Call{Call: _e.mock.On("GetFilesMetadata", userID)}
}

func (_c *MockRepository_GetFilesMetadata_Call) Run(run func(userID uuid.UUID)) *MockRepository_GetFilesMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetFilesMetadata_Call) Return(metadataOutputs []dto.MetadataOutput, err error) *MockRepository_GetFilesMetadata_Call {
	_c.Call.Return(metadataOutputs, err)
	return _c
}

func (_c *MockRepository_GetFilesMetadata_Call) RunAndReturn(run func(userID uuid.UUID) ([]dto.MetadataOutput, error)) *MockRepository_GetFilesMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFileMetadata provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveFileMetadata(info model.MetadataInput) error {
	ret := _mock.Called(info)

	if len(ret) == 0 {
		panic("no return value specified for SaveFileMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(model.MetadataInput) error); ok {
		r0 = returnFunc(info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveFileMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFileMetadata'
type MockRepository_SaveFileMetadata_Call struct {
	*mock.Call
}

// SaveFileMetadata is a helper method to define mock.On call
//   - info model.MetadataInput
func (_e *MockRepository_Expecter) SaveFileMetadata(info interface{}) *MockRepository_SaveFileMetadata_Call {
	return &MockRepository_SaveFileMetadata_Call{Call: _e.mock.On("SaveFileMetadata", info)}
}

func (_c *MockRepository_SaveFileMetadata_Call) Run(run func(info model.MetadataInput)) *MockRepository_SaveFileMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.MetadataInput
		if args[0] != nil {
			arg0 = args[0].(model.MetadataInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_SaveFileMetadata_Call) Return(err error) *MockRepository_SaveFileMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveFileMetadata_Call) RunAndReturn(run func(info model.MetadataInput) error) *MockRepository_SaveFileMetadata_Call {
	_c.Call.Return(run)
	return _c
}
