// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	"github.com/antongolenev23/tuchka-server/internal/entity"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Remove provides a mock function for the type MockStorage
func (_mock *MockStorage) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockStorage_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *MockStorage_Expecter) Remove(path interface{}) *MockStorage_Remove_Call {
	return &MockStorage_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *MockStorage_Remove_Call) Run(run func(path string)) *MockStorage_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorage_Remove_Call) Return(err error) *MockStorage_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_Remove_Call) RunAndReturn(run func(path string) error) *MockStorage_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockStorage
func (_mock *MockStorage) Save(ctx context.Context, fileName string, userID uuid.UUID, r io.Reader) (string, int64, error) {
	ret := _mock.Called(ctx, fileName, userID, r)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, io.Reader) (string, int64, error)); ok {
		return returnFunc(ctx, fileName, userID, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, io.Reader) string); ok {
		r0 = returnFunc(ctx, fileName, userID, r)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, io.Reader) int64); ok {
		r1 = returnFunc(ctx, fileName, userID, r)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, uuid.UUID, io.Reader) error); ok {
		r2 = returnFunc(ctx, fileName, userID, r)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - fileName string
//   - userID uuid.UUID
//   - r io.Reader
func (_e *MockStorage_Expecter) Save(ctx interface{}, fileName interface{}, userID interface{}, r interface{}) *MockStorage_Save_Call {
	return &MockStorage_Save_Call{Call: _e.mock.On("Save", ctx, fileName, userID, r)}
}

func (_c *MockStorage_Save_Call) Run(run func(ctx context.Context, fileName string, userID uuid.UUID, r io.Reader)) *MockStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_Save_Call) Return(path string, size int64, err error) *MockStorage_Save_Call {
	_c.Call.Return(path, size, err)
	return _c
}

func (_c *MockStorage_Save_Call) RunAndReturn(run func(ctx context.Context, fileName string, userID uuid.UUID, r io.Reader) (string, int64, error)) *MockStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// WriteZIP provides a mock function for the type MockStorage
func (_mock *MockStorage) WriteZIP(ctx context.Context, w io.Writer, files []entity.FilePath) error {
	ret := _mock.Called(ctx, w, files)

	if len(ret) == 0 {
		panic("no return value specified for WriteZIP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Writer, []entity.FilePath) error); ok {
		r0 = returnFunc(ctx, w, files)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_WriteZIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteZIP'
type MockStorage_WriteZIP_Call struct {
	*mock.Call
}

// WriteZIP is a helper method to define mock.On call
//   - ctx context.Context
//   - w io.Writer
//   - files []entity.FilePath
func (_e *MockStorage_Expecter) WriteZIP(ctx interface{}, w interface{}, files interface{}) *MockStorage_WriteZIP_Call {
	return &MockStorage_WriteZIP_Call{Call: _e.mock.On("WriteZIP", ctx, w, files)}
}

func (_c *MockStorage_WriteZIP_Call) Run(run func(ctx context.Context, w io.Writer, files []entity.FilePath)) *MockStorage_WriteZIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		var arg2 []entity.FilePath
		if args[2] != nil {
			arg2 = args[2].([]entity.FilePath)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_WriteZIP_Call) Return(err error) *MockStorage_WriteZIP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_WriteZIP_Call) RunAndReturn(run func(ctx context.Context, w io.Writer, files []entity.FilePath) error) *MockStorage_WriteZIP_Call {
	_c.Call.Return(run)
	return _c
}
