services:
  app:
    ports:
      - "127.0.0.1:8443:8443"
    volumes:
      - ./data/storage:/var/lib/tuchka-server
      - ./certs:/certs:ro

  db:
    ports:
      - "127.0.0.1:5433:5432"

  migrations:
    restart: on-failure
    volumes:
      - ./migrations:/migrations