services:
  app:
    ports:
      - "8080:8080"
    volumes:
      - ./data/storage:/var/lib/tuchka-server

  db:
    ports:
      - "127.0.0.1:5433:5432"

  migrations:
    restart: on-failure
    volumes:
      - ./migrations:/migrations