packages:
  github.com/antongolenev23/tuchka-server/internal/repository:
    config:
      dir: internal/mocks
      filename: "{{.InterfaceName | snakecase}}_mock.go"
      pkgname: "mocks"
    interfaces:
      Repository:

  github.com/antongolenev23/tuchka-server/internal/storage:
    config:
      dir: internal/mocks
      filename: "{{.InterfaceName | snakecase}}_mock.go"
      pkgname: "mocks"
    interfaces:
      Storage: