env: "prod" #local, dev, prod
database:
  name: "tuchka"
  user: "appuser"
  sslmode: "disable"
http_server:
  address: "0.0.0.0:8080"
  request_read_timeout: 5s
  response_write_timeout: 5s
  idle_timeout: 60s